In [2]:
#importing library to import the data 
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [3]:
#Reading the data from a csv file
# Chevking whether it was imported correctly
df = pd.read_csv("C:\\Users\\HP\\OneDrive\\Desktop\\Data Science project\\Credit Risk and Loan Default Analysis\\credit-risk-and-loan-default-analysis-dataset.csv\\loan_risk_prediction_dataset.csv")
df.head()

,Age,Income,LoanAmount,CreditScore,YearsExperience,Gender,Education,City,EmploymentType,LoanApproved
0,56,48353.0,31258.0,675.0,20,Female,High School,Houston,Unemployed,0
1,69,57462.0,23262.0,586.0,6,Male,High School,San Francisco,Self-Employed,0
2,46,44219.0,26530.0,781.0,26,Male,PhD,Houston,Self-Employed,1
3,32,56307.0,11531.0,549.0,11,Male,NaN,New York,Unemployed,0
4,60,37034.0,27871.0,500.0,19,Female,High School,Chicago,Unemployed,0

In [4]:
# import sql libraries and moving the data to sql dataframe
import pymysql
from sqlalchemy import create_engine

In [5]:
#Creating a connection betweeen python and sql
engine = create_engine("mysql+pymysql://root:stinos56@localhost:3306/credit_risk_analysis")

In [6]:
# Moving the data to sql database
df.to_sql(
    name = "loan_risk_prediction_dataset",
    con = engine,
    if_exists = "append",
    index = False   
)

5000

In [7]:
%load_ext sql
%sql mysql+pymysql://root:stinos56@localhost:3306/credit_risk_analysis
%config SqlMagic.style = '_DEPRECATED_DEFAULT'

In [8]:
%%sql

SELECT * FROM loan_risk_prediction_dataset LIMIT 5;

 * mysql+pymysql://root:***@localhost:3306/credit_risk_analysis
5 rows affected.

[(56, 48353.0, 31258.0, 675.0, 20, 'Female', 'High School', 'Houston', 'Unemployed', 0),
 (69, 57462.0, 23262.0, 586.0, 6, 'Male', 'High School', 'San Francisco', 'Self-Employed', 0),
 (46, 44219.0, 26530.0, 781.0, 26, 'Male', 'PhD', 'Houston', 'Self-Employed', 1),
 (32, 56307.0, 11531.0, 549.0, 11, 'Male', None, 'New York', 'Unemployed', 0),
 (60, 37034.0, 27871.0, 500.0, 19, 'Female', 'High School', 'Chicago', 'Unemployed', 0)]

In [20]:
# data cleaning and preprocessing 
# Checking for nulls and duplicates 

def data_preprocessing(df):
    #checking for nulls
    nulls = df.isna().sum()
    print("Null values in each column:\n", nulls)
    
    #checking for duplicates
    duplicates = df.duplicated().sum()
    print("Duplicate rows:\n", duplicates)

In [21]:
data_preprocessing(df)

Null values in each column:
 Age                0
Income             0
LoanAmount         0
CreditScore        0
YearsExperience    0
Gender             0
Education          0
City               0
EmploymentType     0
LoanApproved       0
dtype: int64
Duplicate rows:
 0

In [18]:
#data cleaning
#removal of nulls and duplicates 
def data_cleaning(df):
    # remoning nulls 
    if df.isna().sum().sum() > 0:
        df.dropna(inplace = True)
        print("Null values removed.")
    else:
            print("No null values found.")


    #removal of dulicates
    if df.duplicated().sum() > 0:
       df.drop_duplicates(inplace = True)
       print("Duplicate rows removed.")
    else:
       print("No duplicate rows found.")

In [19]:
data_cleaning(df)

Null values removed.
No duplicate rows found.

In [22]:
df.head()

,Age,Income,LoanAmount,CreditScore,YearsExperience,Gender,Education,City,EmploymentType,LoanApproved
0,56,48353.0,31258.0,675.0,20,Female,High School,Houston,Unemployed,0
1,69,57462.0,23262.0,586.0,6,Male,High School,San Francisco,Self-Employed,0
2,46,44219.0,26530.0,781.0,26,Male,PhD,Houston,Self-Employed,1
4,60,37034.0,27871.0,500.0,19,Female,High School,Chicago,Unemployed,0
5,25,47886.0,18106.0,835.0,13,Male,Masters,New York,Salaried,1

In [23]:
df.info()

<class 'pandas.DataFrame'>
Index: 4430 entries, 0 to 4998
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              4430 non-null   int64
 1   Income           4430 non-null   float64
 2   LoanAmount       4430 non-null   float64
 3   CreditScore      4430 non-null   float64
 4   YearsExperience  4430 non-null   int64
 5   Gender           4430 non-null   str
 6   Education        4430 non-null   str
 7   City             4430 non-null   str
 8   EmploymentType   4430 non-null   str
 9   LoanApproved     4430 non-null   int64
dtypes: float64(3), int64(3), str(4)
memory usage: 380.7 KB

In [24]:
df["City"].value_counts()

City
Chicago          1150
San Francisco    1134
Houston          1086
New York         1060
Name: count, dtype: int64

In [25]:
df["EmploymentType"].value_counts()

EmploymentType
Self-Employed    1549
Unemployed       1469
Salaried         1412
Name: count, dtype: int64

In [26]:
df["Gender"].value_counts()

Gender
Male      2248
Female    2182
Name: count, dtype: int64

In [27]:
df["Education"].value_counts()

Education
Bachelors      1134
Masters        1107
PhD            1101
High School    1088
Name: count, dtype: int64

In [29]:
round(df.groupby("Gender")["Income"].mean(), 2)

Gender
Female    49451.16
Male      49906.94
Name: Income, dtype: float64

In [31]:
round(df.groupby("Gender")["LoanAmount"].mean(), 2)

Gender
Female    19845.83
Male      19944.43
Name: LoanAmount, dtype: float64